envVarGroups:
  - name: pharm-agent-shared
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: API_KEY
        value: supersecret
      - key: CORS_ORIGINS
        value: "*"
      - key: WORKER_TOKEN
        value: workertoken
      - key: MINIO_ENDPOINT
        value: ""
      - key: MINIO_ACCESS_KEY
        value: ""
      - key: MINIO_SECRET_KEY
        value: ""

services:
  - type: web
    name: pharm-agent-api
    env: docker
    dockerfilePath: ./backend/Dockerfile
    repo: https://github.com/abhilash0042/pharm-agent
    plan: free
    healthCheckPath: /health
    envVarGroups:
      - name: pharm-agent-shared

  - type: worker
    name: pharm-agent-worker
    env: docker
    dockerfilePath: ./backend/Dockerfile
    dockerCommand: celery -A backend.celery_app worker --loglevel=info
    repo: https://github.com/abhilash0042/pharm-agent
    plan: free
    envVarGroups:
      - name: pharm-agent-shared
