envVarGroups:
  - name: pharm-agent-shared
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: API_KEY
        value: supersecret
      - key: CORS_ORIGINS
        value: "*"
      - key: WORKER_TOKEN
        value: workertoken
      - key: MINIO_ENDPOINT
        value: ""
      - key: MINIO_ACCESS_KEY
        value: ""
      - key: MINIO_SECRET_KEY
        value: ""

services:
  - type: web
    name: pharm-agent-api
    env: docker
    dockerfilePath: ./backend/Dockerfile
    dockerCommand: sh -c "celery -A backend.celery_app worker --loglevel=info & exec gunicorn backend.master_agent.api.main:app -w 2 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT --timeout 120"
    repo: https://github.com/abhilash0042/pharm-agent
    plan: free
    healthCheckPath: /health
    envVars:
      - fromGroup: pharm-agent-shared
